### ISSUE TITLE
[Bug]: Speedometer not working

### ISSUE THREAD

**Issue by SlavicBlin** [Yimura/YimMenu#2557]
### Describe the bug

The speedometer does not show a value instead it stays at 0 and says the vehicle is in reverse.

### Steps To Reproduce

1. Inject
2. Go enable Speedometer
3. Spawn or drive a car
4. Speedo does not go up or down

### Expected Behavior

I would expect the Speedometer to work by showing gears changing and the speed going up or down.

### Logs and/or screenshots

N/A

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Can you see if it's working with the DLL posted by the compile bot here: https://github.com/YimMenu/YimMenu/pull/2561

**Comment by SlavicBlin** [comment]
> Can you see if it's working with the DLL posted by the compile bot here: #2561

Only the gears work now speed still does not seem to show

**Comment by gir489returns** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/100792176/73da145b-50ff-461e-bc5a-7ee4632d9d1c)

I pushed a fix to CVehicle, should be fixed in the next build.

**Comment by SlavicBlin** [comment]
Aight <3

**Comment by D-Borkan** [comment]
> ![image](https://private-user-images.githubusercontent.com/100792176/290686429-73da145b-50ff-461e-bc5a-7ee4632d9d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDAxNzQsIm5iZiI6MTcwMjU5OTg3NCwicGF0aCI6Ii8xMDA3OTIxNzYvMjkwNjg2NDI5LTczZGExNDViLTUwZmYtNDYxZS1iYzVhLTdlZTQ2MzJkOWQxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQwMDI0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjRjMTQ5YTNjNDg1ZmZiYjc5M2FlYzk4MzBlOTFlODk2MjcxNWQ5NjlhOGU4ZDNmYTczNzMwNTMxZTRhZDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mbgUHp8_Ft0XXcWo4Y5EI0fV4-h3olZ2DtGrY_zxSHw)
> 
> I pushed a fix to CVehicle, should be fixed in the next build.

give me some time, i will test it

**Comment by D-Borkan** [comment]
> Can you see if it's working with the DLL posted by the compile bot here: #2553 

so with this build i test it for my post here #2553 
- change session now work fine i change session more time and no crash
- spawn new dlc vehicles now work fine, no crash
- vehicle handling aslo no crash
- speedometer still does not show a value and still 0 but just show the 1, 2, 3, 4 like your pic, i dont know why

i forget to test return vehicles from intercation menu but i think should be fix

- so i will close #2553

**Comment by gir489returns** [comment]
Thanks @D-Borkan.

**Comment by SlavicBlin** [comment]
> > Can you see if it's working with the DLL posted by the compile bot here: #2553
> 
> so with this build i test it for my post here #2553
> 
> * change session now work fine i change session more time and no crash
> * spawn new dlc vehicles now work fine, no crash
> * vehicle handling aslo no crash
> * speedometer still does not show a value and still 0 but just show the 1, 2, 3, 4 like your pic, i dont know why
> 
> i forget to test return vehicles from intercation menu but i think should be fix
> 
> * so i will close [[Bug]: Random crash even with last version #2553](https://github.com/YimMenu/YimMenu/issues/2553)

The merge has not been approved for cvehicles hense why speedometer does not work 👍

**Comment by D-Borkan** [comment]
> > > Can you see if it's working with the DLL posted by the compile bot here: #2553
> > 
> > 
> > so with this build i test it for my post here #2553
> > 
> > * change session now work fine i change session more time and no crash
> > * spawn new dlc vehicles now work fine, no crash
> > * vehicle handling aslo no crash
> > * speedometer still does not show a value and still 0 but just show the 1, 2, 3, 4 like your pic, i dont know why
> > 
> > i forget to test return vehicles from intercation menu but i think should be fix
> > 
> > * so i will close [[Bug]: Random crash even with last version #2553](https://github.com/YimMenu/YimMenu/issues/2553)
> 
> The merge has not been approved for cvehicles hense why speedometer does not work 👍

yeah, i think so and also i will test it later
