### ISSUE TITLE
[Bug]: something broke after new teleport changes

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#2670]
### Describe the bug

- cant teleport into tunnel via waypoint
- cant teleport to water surface (players teleport to sea bed instead)

I have not 100% checked teleportation in tunnel but i am quite sure it does not work as before.

### Steps To Reproduce

- try to mark waypoint on map where you sure is tunnel underneath. 
- try to teleport in water via waypoint. You will get teleported to ground underneath water instead of water surface.

### Expected Behavior

Should work as before right or should add an option something?

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
water related code can be easily fixed by restoring this at the end of `load_ground_at_3dcoord` function

```C++
		float height;
		if (WATER::GET_WATER_HEIGHT(location.x, location.y, location.z, &height))
			location.z = height;
		else
			location.z = ground_z;
```

**Comment by 99Anvar99** [comment]
interesting.... sure thing will add it back

Edit: should now be fixed. 2nd commit in PR #2669

**Comment by lonelybud** [comment]
i think teleporting to tunnel via waypoint is a bad idea so may be that is not a big concern.

**Comment by gir489returns** [comment]
Waypoints should implicitly use the waypoint's coordinates. Sometimes there is no Z component to them, and then we should activate the Z depth calculator. But if it has all 3 cartesian coordinates, I see no reason to not trust it.

**Comment by 99Anvar99** [comment]
I believe this issue should now be closed.
since this PR merged #2669, unless there is still a problem.

**Comment by lonelybud** [comment]
its fine now. thanks for the fix.
